/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmPackage;

import static frmPackage.jfrVehiculoRenta.file;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vehiculoapp.Archivo;
import vehiculoapp.Bus;
import vehiculoapp.Camion;
import vehiculoapp.Coche;
import vehiculoapp.Vehiculo;
import vehiculoapp.furgoneta;

/**
 *
 * @author Neiva
 */
public class jfrBuscarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form jfrBuscarVehiculo
     */
    public jfrBuscarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonBUSCAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelDisponibilidad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelMODELO = new javax.swing.JLabel();
        jLabelMARCA = new javax.swing.JLabel();
        jLabelCOLOR = new javax.swing.JLabel();
        jLabelKILOMETRAJE = new javax.swing.JLabel();
        jLabelCILINDRAJE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel1.setText("DISPONIBILIDAD:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 297, 167, 25);

        jTextField1.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(428, 42, 287, 25);

        jButtonBUSCAR.setText("BUSCAR");
        jButtonBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBUSCARMouseClicked(evt);
            }
        });
        jButtonBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBUSCAR);
        jButtonBUSCAR.setBounds(765, 45, 100, 23);

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INGRESE LA MATRICULA DEL VEHICULO:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(21, 38, 400, 25);

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel3.setText("MODELO:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(47, 140, 80, 25);

        jLabelMatricula.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jPanel1.add(jLabelMatricula);
        jLabelMatricula.setBounds(160, 100, 137, 24);
        jPanel1.add(jLabelDisponibilidad);
        jLabelDisponibilidad.setBounds(140, 300, 589, 25);

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel4.setText("MATRICULA:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(47, 97, 100, 25);

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel5.setText("KILOMETRAJE:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 140, 120, 25);

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel6.setText("CILINDRAJE:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 190, 100, 25);

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel7.setText("COLOR:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 100, 70, 25);

        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel8.setText("MARCA:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 190, 70, 25);

        jLabelMODELO.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jPanel1.add(jLabelMODELO);
        jLabelMODELO.setBounds(150, 140, 137, 24);

        jLabelMARCA.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jPanel1.add(jLabelMARCA);
        jLabelMARCA.setBounds(150, 190, 137, 24);

        jLabelCOLOR.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jPanel1.add(jLabelCOLOR);
        jLabelCOLOR.setBounds(470, 100, 137, 24);

        jLabelKILOMETRAJE.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jPanel1.add(jLabelKILOMETRAJE);
        jLabelKILOMETRAJE.setBounds(470, 140, 137, 24);

        jLabelCILINDRAJE.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jPanel1.add(jLabelCILINDRAJE);
        jLabelCILINDRAJE.setBounds(470, 190, 137, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBUSCARMouseClicked
      ArrayList <Vehiculo>arr = new ArrayList <Vehiculo>();
        File f =new File(file);
        int cont =0;
        if(f.exists()){
             Archivo a = new Archivo();
         arr=  a.leerArchivo(file);
            for (int i = 0; i < arr.size(); i++) {
                if(arr.get(i).getMatricula().equals(this.jTextField1.getText())){
                     if((arr.get(i)).isDisponibilidad()){
                         String dis = "No Alquilado";
                             this.jLabelMatricula.setText(arr.get(i).getMatricula());
                             this.jLabelDisponibilidad.setText(dis);
                             if(arr.get(i) instanceof Coche){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((Coche)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((Coche)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((Coche)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((Coche)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((Coche)arr.get(i)).getModelo()));
                             }
                             if(arr.get(i) instanceof Bus){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((Bus)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((Bus)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((Bus)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((Bus)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((Bus)arr.get(i)).getModelo()));
                             }
                             if(arr.get(i) instanceof Camion){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((Camion)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((Camion)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((Camion)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((Camion)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((Camion)arr.get(i)).getModelo()));
                             }
                             if(arr.get(i) instanceof furgoneta){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((furgoneta)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((furgoneta)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((furgoneta)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((furgoneta)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((furgoneta)arr.get(i)).getModelo()));
                             }
                   
                          
                    break;
              
            }else{
                         String dis = "Alquilado";
                             this.jLabelMatricula.setText(arr.get(i).getMatricula());
                    this.jLabelDisponibilidad.setText(dis);
                    if(arr.get(i) instanceof Coche){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((Coche)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((Coche)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((Coche)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((Coche)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((Coche)arr.get(i)).getModelo()));
                             }
                             if(arr.get(i) instanceof Bus){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((Bus)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((Bus)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((Bus)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((Bus)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((Bus)arr.get(i)).getModelo()));
                             }
                             if(arr.get(i) instanceof Camion){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((Camion)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((Camion)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((Camion)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((Camion)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((Camion)arr.get(i)).getModelo()));
                             }
                             if(arr.get(i) instanceof furgoneta){
                                 this.jLabelCILINDRAJE.setText(String.valueOf(((furgoneta)arr.get(i)).getCilindrada()));
                                 this.jLabelCOLOR.setText(String.valueOf(((furgoneta)arr.get(i)).getColor()));
                                 this.jLabelKILOMETRAJE.setText(String.valueOf(((furgoneta)arr.get(i)).getKilometraje()));
                                 this.jLabelMARCA.setText(String.valueOf(((furgoneta)arr.get(i)).getMarca()));
                                 this.jLabelMODELO.setText(String.valueOf(((furgoneta)arr.get(i)).getModelo()));
                             }
                     
                    break;
            }
                
                }
                cont++;
            }
            if(arr.size()==cont){
                JOptionPane.showMessageDialog(null, "El Vehiculo no Existe en nuestro Patio");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Error, No Existen Vehiculos Para Buscar");
        }
    }//GEN-LAST:event_jButtonBUSCARMouseClicked

    private void jButtonBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBUSCARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrBuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrBuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrBuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrBuscarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrBuscarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBUSCAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCILINDRAJE;
    private javax.swing.JLabel jLabelCOLOR;
    private javax.swing.JLabel jLabelDisponibilidad;
    private javax.swing.JLabel jLabelKILOMETRAJE;
    private javax.swing.JLabel jLabelMARCA;
    private javax.swing.JLabel jLabelMODELO;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
public void alquilar(Vehiculo o){
    o.setDisponibilidad(false);
}
}
