/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmPackage;

import static frmPackage.jfrVehiculoRenta.file;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import vehiculoapp.Archivo;
import vehiculoapp.Bus;
import vehiculoapp.Camion;
import vehiculoapp.Coche;
import vehiculoapp.VehiculoCarga;
import vehiculoapp.VehiculoPasajeros;
import vehiculoapp.Vehiculo;
import vehiculoapp.furgoneta;

/**
 *
 * @author Miguel
 */
public class jfrEditarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form jfrEditarCoche
     */
     String file ="Coches.txt";
 String C[]={"N°","Matricula","Numero de Pasajeros","Modelo","Marca","Color","Kilometraje","Cilindrada"
         ,"Tipo de Combustión","Tipo Vehiculo","Numero de Llantas","Tonelaje"};
String D[][]={};
DefaultTableModel model;  
ArrayList <Vehiculo>arr;

    public jfrEditarVehiculo() {
        initComponents();
        
        this.setLocationRelativeTo(null);
         
         setIconImage(new ImageIcon(getClass().getResource("/imagenes/rentCar.png")).getImage());
       listar();
    }
   public void listar(){
        int cont=0;
        File f =new File(file);
        if(f.exists()){
             Archivo a = new Archivo();
         arr=  a.leerArchivo(file);
        
    model = new DefaultTableModel(D,C);
    this.jTableEditarVehiculo.setModel(model);
       
    while(arr!=null){
        int k=cont+1;
        if(arr.get(cont) instanceof Coche){
            ArrayList <Coche>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),n.get(cont).getNumPasajeros(),n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),"No Disponible","No Disponible"};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof Bus){
            ArrayList <Bus>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),n.get(cont).getNumPasajeros(),n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),"No Disponible","No Disponible"};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof furgoneta){
            ArrayList <furgoneta>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),"No Disponible",n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),n.get(cont).getNumllantas()
            ,n.get(cont).getTonelaje()};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof Camion){
            ArrayList <Camion>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),"No Disponible",n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),n.get(cont).getNumllantas()
            ,n.get(cont).getTonelaje()};
      this.model.addRow(O);
      cont++;
        }
    
      
      if(cont>=arr.size()){
          break;
      }   
    } 
 }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEditarVehiculo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldnumPas = new javax.swing.JTextField();
        jTextFieldMod = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldKilometraje = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldCilindraje = new javax.swing.JTextField();
        jTextFieldCombustible = new javax.swing.JTextField();
        jButtonEditarVehiculo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelpos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumLlantas = new javax.swing.JTextField();
        jTextFieldTonelaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(229, 226, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)), "Seleccione un Elemento de la Lista para Editar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 0, 18))); // NOI18N

        jTableEditarVehiculo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableEditarVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jTableEditarVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEditarVehiculo.setRowHeight(40);
        jTableEditarVehiculo.setRowMargin(6);
        jTableEditarVehiculo.setShowHorizontalLines(false);
        jTableEditarVehiculo.setShowVerticalLines(false);
        jTableEditarVehiculo.getTableHeader().setResizingAllowed(false);
        jTableEditarVehiculo.getTableHeader().setReorderingAllowed(false);
        jTableEditarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEditarVehiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEditarVehiculo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 1, new java.awt.Color(0, 102, 153)), "Características del Coche", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel2.setText("NUMERO DE PASAJEROS:");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel3.setText("MODELO:");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel4.setText("MARCA:");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel5.setText("COLOR:");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel6.setText("KILOMETRAJE:");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel7.setText("MATRICULA:");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel8.setText("CILINDRAJE:");

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel9.setText("COMBUSTIBLE:");

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel1.setText("TIPO DE VEHICULO:");

        jTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaActionPerformed(evt);
            }
        });

        jTextFieldCilindraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCilindrajeActionPerformed(evt);
            }
        });

        jButtonEditarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1488536281_compose.png"))); // NOI18N
        jButtonEditarVehiculo.setBorder(null);
        jButtonEditarVehiculo.setBorderPainted(false);
        jButtonEditarVehiculo.setFocusable(false);
        jButtonEditarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarVehiculoMouseClicked(evt);
            }
        });
        jButtonEditarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarVehiculoActionPerformed(evt);
            }
        });

        jLabel10.setText("Posicion");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1488554958_DeleteRed.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel11.setText("Numero Llantas :");

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jLabel12.setText("Tonelaje:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldMod)
                                    .addComponent(jTextFieldnumPas)
                                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldColor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldKilometraje, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabelpos)
                                .addGap(252, 252, 252)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonEditarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldTonelaje, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldNumLlantas))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jTextFieldCombustible))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldnumPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldNumLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldTonelaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabelpos))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableEditarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEditarVehiculoMouseClicked
        Archivo g = new Archivo();
        
        
        
        int selection = this.jTableEditarVehiculo.rowAtPoint(evt.getPoint());
        
        if( (arr.get(selection) instanceof Coche)||(arr.get(selection) instanceof Bus) ){
            ArrayList <VehiculoPasajeros> n = g.leerArchivo(file);
            this.jTextFieldTipo.setText(n.get(selection).getTipo());
       this.jTextFieldnumPas.setText(String.valueOf(n.get(selection).getNumPasajeros()));
       this.jTextFieldMod.setText(n.get(selection).getModelo() );
       this.jTextFieldMarca.setText(n.get(selection).getMarca() );
       this.jTextFieldColor.setText(n.get(selection).getColor() );
       this.jTextFieldKilometraje.setText(String.valueOf(n.get(selection).getKilometraje()) );
       this.jTextFieldMatricula.setText(n.get(selection).getMatricula() );
       this.jTextFieldCilindraje.setText(String.valueOf(n.get(selection).getCilindrada()) );
       this.jTextFieldCombustible.setText(n.get(selection).getCombustible() );
       this.jTextFieldNumLlantas.setEnabled(false);
        this.jTextFieldNumLlantas.setEditable(false);
       this.jTextFieldTonelaje.setEnabled(false);
       this.jTextFieldTonelaje.setEditable(false);
       this.jTextFieldnumPas.setEnabled(true);
       this.jTextFieldnumPas.setEditable(true);
       this.jTextFieldTipo.setEditable(false);
       //this.jTextFieldTipo.setEnabled(false);
       this.jLabelpos.setText(String.valueOf(jTableEditarVehiculo.getValueAt(selection, 0)) );
        }else if((arr.get(selection) instanceof furgoneta)||(arr.get(selection) instanceof Camion)){
            ArrayList <VehiculoCarga> n = g.leerArchivo(file);
            this.jTextFieldTipo.setText(n.get(selection).getTipo());
       this.jTextFieldnumPas.setText("No Disponible en Vehiculos de Carga");
       this.jTextFieldMod.setText(n.get(selection).getModelo() );
       this.jTextFieldMarca.setText(n.get(selection).getMarca() );
       this.jTextFieldColor.setText(n.get(selection).getColor() );
       this.jTextFieldKilometraje.setText(String.valueOf(n.get(selection).getKilometraje()) );
       this.jTextFieldMatricula.setText(n.get(selection).getMatricula() );
       this.jTextFieldCilindraje.setText(String.valueOf(n.get(selection).getCilindrada()) );
       this.jTextFieldCombustible.setText(n.get(selection).getCombustible() );
       this.jTextFieldNumLlantas.setText(String.valueOf(n.get(selection).getNumllantas()));
       this.jTextFieldTonelaje.setText(String.valueOf(n.get(selection).getTonelaje()));
       this.jLabelpos.setText(String.valueOf(jTableEditarVehiculo.getValueAt(selection, 0)) );
       this.jTextFieldNumLlantas.setEnabled(true);
        this.jTextFieldNumLlantas.setEditable(true);
       this.jTextFieldTonelaje.setEnabled(true);
       this.jTextFieldTonelaje.setEditable(true);
       this.jTextFieldnumPas.setEnabled(false);
       this.jTextFieldnumPas.setEditable(false);
        this.jTextFieldTipo.setEditable(false);
     //  this.jTextFieldTipo.setEnabled(false);
        }
            
        
       
    }//GEN-LAST:event_jTableEditarVehiculoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEditarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarVehiculoActionPerformed

    }//GEN-LAST:event_jButtonEditarVehiculoActionPerformed

    private void jButtonEditarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarVehiculoMouseClicked
        Archivo g = new Archivo();

        if( (this.jTextFieldTipo.getText().equals("Coche"))){
            arr=g.leerArchivo(file);
            int selection = (this.jTableEditarVehiculo.rowAtPoint(evt.getPoint()));

            int p=Integer.parseInt(this.jLabelpos.getText())-1;
            int s = ((Integer.parseInt(jTableEditarVehiculo.getValueAt(selection, 0).toString())));
            Coche  c= new Coche(Integer.parseInt(this.jTextFieldnumPas.getText()),this.jTextFieldMod.getText(),
                this.jTextFieldMarca.getText(),this.jTextFieldColor.getText(),Integer.parseInt(this.jTextFieldKilometraje.getText()),
                Integer.parseInt(this.jTextFieldCilindraje.getText()),
                this.jTextFieldCombustible.getText(),this.jTextFieldTipo.getText(),
                this.jTextFieldMatricula.getText());
            arr.set(p, c);
            sobreescribirDatos();

        } else  if(this.jTextFieldTipo.getText().equals("Bus")){

            int selection = (this.jTableEditarVehiculo.rowAtPoint(evt.getPoint()));
            int m=(int) this.jTableEditarVehiculo.getValueAt(selection, 0);
            int p=Integer.parseInt(this.jLabelpos.getText())-1;
            int s = ((Integer.parseInt(jTableEditarVehiculo.getValueAt(selection, 0).toString())));
            Bus  b= new Bus(Integer.parseInt(this.jTextFieldnumPas.getText()),this.jTextFieldMod.getText(),
                this.jTextFieldMarca.getText(),this.jTextFieldColor.getText(),Integer.parseInt(this.jTextFieldKilometraje.getText()),
                Integer.parseInt(this.jTextFieldCilindraje.getText()),
                this.jTextFieldCombustible.getText(),this.jTextFieldTipo.getText(),
                this.jTextFieldMatricula.getText());
            arr.set(p, b);
            sobreescribirDatos();

        }else  if(this.jTextFieldTipo.getText().equals("Furgoneta")){

            int selection = (this.jTableEditarVehiculo.rowAtPoint(evt.getPoint()));
            int m=(int) this.jTableEditarVehiculo.getValueAt(selection, 0);
            int p=Integer.parseInt(this.jLabelpos.getText())-1;
            int s = ((Integer.parseInt(jTableEditarVehiculo.getValueAt(selection, 0).toString())));
            furgoneta  fur= new furgoneta(Integer.parseInt(this.jTextFieldNumLlantas.getText()),Float.parseFloat(this.jTextFieldTonelaje.getText()),this.jTextFieldMod.getText(),
                this.jTextFieldMarca.getText(),this.jTextFieldColor.getText(),Integer.parseInt(this.jTextFieldKilometraje.getText()),
                Integer.parseInt(this.jTextFieldCilindraje.getText()),
                this.jTextFieldCombustible.getText(),this.jTextFieldTipo.getText(),
                this.jTextFieldMatricula.getText());
            arr.set(p, fur);
            sobreescribirDatos();

        }else  if(this.jTextFieldTipo.getText().equals("Camión")){

            int selection = (this.jTableEditarVehiculo.rowAtPoint(evt.getPoint()));
            int m=(int) this.jTableEditarVehiculo.getValueAt(selection, 0);
            int p=Integer.parseInt(this.jLabelpos.getText())-1;
            int s = ((Integer.parseInt(jTableEditarVehiculo.getValueAt(selection, 0).toString())));
            Camion  camion= new Camion(Integer.parseInt(this.jTextFieldNumLlantas.getText()),Float.parseFloat(this.jTextFieldTonelaje.getText()),this.jTextFieldMod.getText(),
                this.jTextFieldMarca.getText(),this.jTextFieldColor.getText(),Integer.parseInt(this.jTextFieldKilometraje.getText()),
                Integer.parseInt(this.jTextFieldCilindraje.getText()),
                this.jTextFieldCombustible.getText(),this.jTextFieldTipo.getText(),
                this.jTextFieldMatricula.getText());
            arr.set(p, camion);
            sobreescribirDatos();

        }

    }//GEN-LAST:event_jButtonEditarVehiculoMouseClicked

    private void jTextFieldCilindrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCilindrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCilindrajeActionPerformed

    private void jTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaActionPerformed
public void sobreescribirDatos(){
     FileOutputStream fos;
            File f= new File(file);
            ObjectOutputStream ous;
            f.delete();
            ArrayList<Coche> co = new ArrayList<Coche>();
            ArrayList<Bus> bus = new ArrayList<Bus>();
            ArrayList<furgoneta> furgo = new ArrayList<furgoneta>();
            ArrayList<Camion> cam = new ArrayList<Camion>();
            for (int i = 0; i < arr.size(); i++) {
                try {
                    fos= new FileOutputStream(f,true);
                    ous = new ObjectOutputStream(fos);
                    if(arr.get(i) instanceof Coche){
                        co.add((Coche) arr.get(i));
                        co.set(0,(Coche) arr.get(i));
                        Coche  n= new Coche(co.get(0).getNumPasajeros(),co.get(0).getModelo(),co.get(0).getMarca(),
                                co.get(0).getColor(),co.get(0).getKilometraje(),co.get(0).getCilindrada(),co.get(0).getCombustible()
                                ,co.get(0).getTipo(),co.get(0).getMatricula());
                        ous.writeObject(n);
                    }else if(arr.get(i) instanceof Bus){
                         bus.add((Bus) arr.get(i));
                        bus.set(0,(Bus) arr.get(i));
                        Bus  a= new Bus(bus.get(0).getNumPasajeros(),bus.get(0).getModelo(),bus.get(0).getMarca(),
                                bus.get(0).getColor(),bus.get(0).getKilometraje(),bus.get(0).getCilindrada(),bus.get(0).getCombustible()
                                ,bus.get(0).getTipo(),bus.get(0).getMatricula());
                        ous.writeObject(a);
                    }else if(arr.get(i) instanceof furgoneta){
                        furgo.add((furgoneta) arr.get(i)); 
                        furgo.set(0,(furgoneta) arr.get(i));
                        furgoneta  e= new furgoneta(furgo.get(0).getNumllantas(),furgo.get(0).getTonelaje(),furgo.get(0).getModelo(),furgo.get(0).getMarca(),
                                furgo.get(0).getColor(),furgo.get(0).getKilometraje(),furgo.get(0).getCilindrada(),furgo.get(0).getCombustible()
                                ,furgo.get(0).getTipo(),furgo.get(0).getMatricula());
                        ous.writeObject(e);
                    }else if(arr.get(i) instanceof Camion){
                        cam.add((Camion) arr.get(i)); 
                        cam.set(0,(Camion) arr.get(i));
                        Camion  e= new Camion(cam.get(0).getNumllantas(),cam.get(0).getTonelaje(),cam.get(0).getModelo(),cam.get(0).getMarca(),
                                cam.get(0).getColor(),cam.get(0).getKilometraje(),cam.get(0).getCilindrada(),cam.get(0).getCombustible()
                                ,cam.get(0).getTipo(),cam.get(0).getMatricula());
                        ous.writeObject(e);
                    }
ous.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
             
        dispose();
        
        
}        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrEditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrEditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrEditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrEditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrEditarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelpos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEditarVehiculo;
    private javax.swing.JTextField jTextFieldCilindraje;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldCombustible;
    private javax.swing.JTextField jTextFieldKilometraje;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldMod;
    private javax.swing.JTextField jTextFieldNumLlantas;
    private javax.swing.JTextField jTextFieldTipo;
    private javax.swing.JTextField jTextFieldTonelaje;
    private javax.swing.JTextField jTextFieldnumPas;
    // End of variables declaration//GEN-END:variables
}
