/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmPackage;

import static frmPackage.jfrVehiculoRenta.file;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import vehiculoapp.Archivo;
import vehiculoapp.Bus;
import vehiculoapp.Camion;
import vehiculoapp.Coche;
import vehiculoapp.VehiculoPasajeros;
import vehiculoapp.Vehiculo;
import vehiculoapp.furgoneta;

/**
 *
 * @author Laptop Toshiba
 */
public class jfrElim extends javax.swing.JFrame {
String file ="Coches.txt";
static String C[]={"N°","Matricula","Numero de Pasajeros","Modelo","Marca","Color","Kilometraje","Cilindrada"
         ,"Tipo de Combustión","Tipo Vehiculo","Numero de Llantas","Tonelaje"};
String D[][]={};
DefaultTableModel model;  
ArrayList <Vehiculo>arr;
    /**
     * Creates new form jfrElim
     */
    public jfrElim() {
        initComponents();
        this.setLocationRelativeTo(null);
         setIconImage(new ImageIcon(getClass().getResource("/imagenes/rentCar.png")).getImage());
        listar();
    }

    public void listar(){
        int cont=0;
        File f =new File(file);
        if(f.exists()){
             Archivo a = new Archivo();
         arr=  a.leerArchivo(file);
        
    model = new DefaultTableModel(D,C);
    this.jTable1.setModel(model);
       
    while(arr!=null){
        int k=cont+1;
        if(arr.get(cont) instanceof Coche){
            ArrayList <Coche>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),n.get(cont).getNumPasajeros(),n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),"No Disponible","No Disponible"};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof Bus){
            ArrayList <Bus>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),n.get(cont).getNumPasajeros(),n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),"No Disponible","No Disponible"};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof furgoneta){
            ArrayList <furgoneta>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),"No Disponible",n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),n.get(cont).getNumllantas()
            ,n.get(cont).getTonelaje()};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof Camion){
            ArrayList <Camion>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),"No Disponible",n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),n.get(cont).getNumllantas()
            ,n.get(cont).getTonelaje()};
      this.model.addRow(O);
      cont++;
        }
    
      
      if(cont>=arr.size()){
          break;
      }   
    } 
 }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Seleccione un ITEM de la Tabla \n2. Despues presione el icono 'X'\n    para poder eliminarlo.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(35);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1488554958_DeleteRed.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(109, 109, 109)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 560, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int selection = this.jTable1.rowAtPoint(evt.getPoint());
        this.jLabel1.setText(String.valueOf(jTable1.getValueAt(selection, 0)) );
    }//GEN-LAST:event_jTable1MouseClicked
public void sobreescribirDatos(){
     FileOutputStream fos;
            File f= new File(file);
            ObjectOutputStream ous;
            f.delete();
            ArrayList<Coche> co = new ArrayList<Coche>();
            ArrayList<Bus> bus = new ArrayList<Bus>();
            ArrayList<furgoneta> furgo = new ArrayList<furgoneta>();
            ArrayList<Camion> cam = new ArrayList<Camion>();
            for (int i = 0; i < arr.size(); i++) {
                try {
                    fos= new FileOutputStream(f,true);
                    ous = new ObjectOutputStream(fos);
                    if(arr.get(i) instanceof Coche){
                        co.add((Coche) arr.get(i));
                        co.set(0,(Coche) arr.get(i));
                        Coche  n= new Coche(co.get(0).getNumPasajeros(),co.get(0).getModelo(),co.get(0).getMarca(),
                                co.get(0).getColor(),co.get(0).getKilometraje(),co.get(0).getCilindrada(),co.get(0).getCombustible()
                                ,co.get(0).getTipo(),co.get(0).getMatricula());
                        ous.writeObject(n);
                    }else if(arr.get(i) instanceof Bus){
                         bus.add((Bus) arr.get(i));
                        bus.set(0,(Bus) arr.get(i));
                        Bus  a= new Bus(bus.get(0).getNumPasajeros(),bus.get(0).getModelo(),bus.get(0).getMarca(),
                                bus.get(0).getColor(),bus.get(0).getKilometraje(),bus.get(0).getCilindrada(),bus.get(0).getCombustible()
                                ,bus.get(0).getTipo(),bus.get(0).getMatricula());
                        ous.writeObject(a);
                    }else if(arr.get(i) instanceof furgoneta){
                        furgo.add((furgoneta) arr.get(i)); 
                        furgo.set(0,(furgoneta) arr.get(i));
                        furgoneta  e= new furgoneta(furgo.get(0).getNumllantas(),furgo.get(0).getTonelaje(),furgo.get(0).getModelo(),furgo.get(0).getMarca(),
                                furgo.get(0).getColor(),furgo.get(0).getKilometraje(),furgo.get(0).getCilindrada(),furgo.get(0).getCombustible()
                                ,furgo.get(0).getTipo(),furgo.get(0).getMatricula());
                        ous.writeObject(e);
                    }else if(arr.get(i) instanceof Camion){
                        cam.add((Camion) arr.get(i)); 
                        cam.set(0,(Camion) arr.get(i));
                        Camion  e= new Camion(cam.get(0).getNumllantas(),cam.get(0).getTonelaje(),cam.get(0).getModelo(),cam.get(0).getMarca(),
                                cam.get(0).getColor(),cam.get(0).getKilometraje(),cam.get(0).getCilindrada(),cam.get(0).getCombustible()
                                ,cam.get(0).getTipo(),cam.get(0).getMatricula());
                        ous.writeObject(e);
                    }
ous.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
             
        dispose();
        
        
}
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Archivo g = new Archivo();
        int a = (Integer.parseInt(this.jLabel1.getText()))-1;
        arr=g.leerArchivo(file);
        FileOutputStream fos;
        arr.remove(a);
        sobreescribirDatos();
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrElim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrElim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrElim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrElim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrElim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
