/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmPackage;

import static frmPackage.jfrVehiculoRenta.file;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import vehiculoapp.Archivo;
import vehiculoapp.Bus;
import vehiculoapp.Camion;
import vehiculoapp.Coche;
import vehiculoapp.VehiculoPasajeros;
import vehiculoapp.Vehiculo;
import vehiculoapp.furgoneta;

/**
 *
 * @author Miguel
 */
public class jfrPreciosAlquiler extends javax.swing.JFrame {

   String file ="Coches.txt";
String C[]={"N°","Matricula","Numero de Pasajeros","Modelo","Marca","Color","Kilometraje","Cilindrada"
         ,"Tipo de Combustión","Tipo Vehiculo","Numero de Llantas","Tonelaje","Precio de Alquiler"};
String D[][]={};
DefaultTableModel model;  
ArrayList <Vehiculo>arr;
    public jfrPreciosAlquiler() {
        initComponents();
        this.setLocationRelativeTo(null);
         setIconImage(new ImageIcon(getClass().getResource("/imagenes/rentCar.png")).getImage());
        listar();
    }
public void listar(){
        int cont=0;
        File f =new File(file);
        if(f.exists()){
             Archivo a = new Archivo();
         arr=  a.leerArchivo(file);
        
    model = new DefaultTableModel(D,C);
    this.jTable1.setModel(model);
       
    while(arr!=null){
        int k=cont+1;
        if(arr.get(cont) instanceof Coche){
            ArrayList <Coche>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),n.get(cont).getNumPasajeros(),n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),"No Disponible","No Disponible"
                    ,n.get(cont).precioAlquiler(Integer.parseInt(this.jTextFielddIAS.getText()))};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof Bus){
            ArrayList <Bus>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),n.get(cont).getNumPasajeros(),n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),"No Disponible","No Disponible"
            ,n.get(cont).precioAlquiler(Integer.parseInt(this.jTextFielddIAS.getText()))};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof furgoneta){
            ArrayList <furgoneta>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),"No Disponible",n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),n.get(cont).getNumllantas()
            ,n.get(cont).getTonelaje(),n.get(cont).precioAlquiler(Integer.parseInt(this.jTextFielddIAS.getText()))};
      this.model.addRow(O);
      cont++;
        }else if(arr.get(cont) instanceof Camion){
            ArrayList <Camion>  n = a.leerArchivo(file);
            Object O[]={k,n.get(cont).getMatricula(),"No Disponible",n.get(cont).getModelo()
    ,n.get(cont).getMarca(),n.get(cont).getColor(),n.get(cont).getKilometraje(),
    n.get(cont).getCilindrada(),n.get(cont).getCombustible(),n.get(cont).getTipo(),n.get(cont).getNumllantas()
            ,n.get(cont).getTonelaje(),n.get(cont).precioAlquiler(Integer.parseInt(this.jTextFielddIAS.getText()))};
      this.model.addRow(O);
      cont++;
        }
    
      
      if(cont>=arr.size()){
          break;
      }   
    } 
 }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFielddIAS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(45);
        jTable1.setShowHorizontalLines(false);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Batang", 3, 18)); // NOI18N
        jLabel1.setText("DIAS:");

        jTextFielddIAS.setFont(new java.awt.Font("Goudy Stout", 0, 11)); // NOI18N
        jTextFielddIAS.setText("5");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFielddIAS, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFielddIAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrPreciosAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrPreciosAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrPreciosAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrPreciosAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrPreciosAlquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFielddIAS;
    // End of variables declaration//GEN-END:variables
}
